### ISSUE TITLE
Surface mesh displacement results

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/pywim#70]
Add the displacements of the vertices of a surface mesh to the Smart Slice result object.

**Comment by jlselden** [comment]
Add an attribute named `surface_mesh_results` to the `pywim.smartslice.result.Result` object that gets returned from smartslice. This new attribute will be a `pywim.fea.result.Databse` object.

**Comment by jlselden** [comment]
Resolved in https://github.com/tetonsim/pywim/commit/49ce788232642711c2ec479145f6e46e828693a5
