### ISSUE TITLE
Problem area regions

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/pywim#71]
Add the high strain and low FOS region (meshes or bounding boxes?) to the Smart Slice result object.

**Comment by jlselden** [comment]
@bradymadams Do we want separate attributes for each type of problem region? For example, one for high strain and another one for low safety factor. I could see other potential reasons for identifying regions in the model, and having separate attributes for each could get messy. We could create a single attribute called something like `regions_of_interest` consisting of a list of objects with a name describing the region, e.g., high_strain or low_fos, and a list of bounding boxes.

**Comment by bradymadams** [comment]
I would probably try to stay close to the way the `Increment.node_results`, etc. work. Use a `WimList(T)` where T is some class that represents a problem region result, and it must have a `name` attribute. This allows for `[ ]` operator access by name (see `WimList.__getitem__` for more details on that.

We'll also need to make sure we set it up for extensibility to multiple steps and increments.

**Comment by jlselden** [comment]
Got it.

**Comment by jlselden** [comment]
Would it make sense to add an attribute to the `pywim.fea.result.ModelResults` object that is a `WimList` containing the problem regions? This would build in the step/increment structure automatically. Maybe `ModelResults` isn't the best place for it, but it would feel like duplicating a lot of code if we want the step/increment structure and don't use `Database`.

**Comment by bradymadams** [comment]
Yeah, that sounds like it could work nicely.
